[pytest]
addopts = -p no:langsmith_plugin --cov=. --cov-report=term-missing --cov-config=.coveragerc
cache_dir = .pytest_cache
testpaths = tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::pytest.PytestDeprecationWarning
    ignore::DeprecationWarning
