import { z } from 'zod'

export const navigationDomainIdSchema = z.enum([
  'assistant',
  'workbench',
  'automations',
  'library',
  'activity',
])

export const navigationIconKeySchema = navigationDomainIdSchema

export const navigationPlatformSchema = z.enum(['web', 'desktop', 'android'])
export const navigationMinimumReadinessSchema = z.enum([
  'experimental',
  'beta',
  'stable',
])
export const navigationDeepLinkRuleSchema = z.enum([
  'canonical',
  'canonicalWithDescendants',
])
export const navigationSelectedStateRuleSchema = z.enum([
  'prefix',
  'longestPrefix',
])

export const navigationEntrySchema = z.object({
  id: z.string().min(1),
  canonicalPath: z.string().startsWith('/'),
  labelKey: z.string().min(1),
  legacyPaths: z.array(z.string().startsWith('/')),
  matchPrefixes: z.array(z.string().startsWith('/')).min(1),
  order: z.number().int().positive(),
  requiredCapability: z.string().regex(/^[a-z][a-z0-9_]*:[a-z][a-z0-9_]*$/).nullable(),
  featureFlag: z.string().min(1).nullable(),
  platforms: z.array(navigationPlatformSchema).min(1),
  minimumReadiness: navigationMinimumReadinessSchema,
  offlineAvailable: z.boolean(),
  requiresProjectContext: z.boolean(),
  deepLinkRule: navigationDeepLinkRuleSchema,
  selectedStateRule: navigationSelectedStateRuleSchema,
}).strict()

export const navigationDomainSchema = navigationEntrySchema.extend({
  id: navigationDomainIdSchema,
  iconKey: navigationIconKeySchema,
  children: z.array(navigationEntrySchema).min(1),
}).strict()

export const navigationManifestSchema = z.object({
  version: z.literal(2),
  domains: z.array(navigationDomainSchema).length(5),
}).strict()

export type NavigationDomainId = z.infer<typeof navigationDomainIdSchema>
export type NavigationIconKey = z.infer<typeof navigationIconKeySchema>
export type NavigationPlatform = z.infer<typeof navigationPlatformSchema>
export type NavigationMinimumReadiness = z.infer<typeof navigationMinimumReadinessSchema>
export type NavigationDeepLinkRule = z.infer<typeof navigationDeepLinkRuleSchema>
export type NavigationSelectedStateRule = z.infer<typeof navigationSelectedStateRuleSchema>
export type NavigationEntry = z.infer<typeof navigationEntrySchema>
export type NavigationDomain = z.infer<typeof navigationDomainSchema>
export type NavigationManifest = z.infer<typeof navigationManifestSchema>

const rawNavigationManifest = {
  version: 2,
  domains: [
    {
      id: 'assistant',
      canonicalPath: '/assistant',
      labelKey: 'nav.domain.assistant',
      iconKey: 'assistant',
      legacyPaths: ['/chat'],
      matchPrefixes: ['/assistant'],
      order: 10,
      requiredCapability: null,
      featureFlag: null,
      platforms: ['web'],
      minimumReadiness: 'stable',
      offlineAvailable: false,
      requiresProjectContext: false,
      deepLinkRule: 'canonicalWithDescendants',
      selectedStateRule: 'prefix',
      children: [
        {
          id: 'assistant.current',
          canonicalPath: '/assistant',
          labelKey: 'nav.assistant.current',
          legacyPaths: ['/chat'],
          matchPrefixes: ['/assistant'],
          order: 10,
          requiredCapability: 'chat:send',
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'assistant.sessions',
          canonicalPath: '/assistant/sessions',
          labelKey: 'nav.assistant.sessions',
          legacyPaths: [],
          matchPrefixes: ['/assistant/sessions'],
          order: 20,
          requiredCapability: 'chat:history',
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonicalWithDescendants',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'assistant.context',
          canonicalPath: '/assistant/context',
          labelKey: 'nav.assistant.context',
          legacyPaths: [],
          matchPrefixes: ['/assistant/context'],
          order: 30,
          requiredCapability: 'memory:read',
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
      ],
    },
    {
      id: 'workbench',
      canonicalPath: '/workbench/projects',
      labelKey: 'nav.domain.workbench',
      iconKey: 'workbench',
      legacyPaths: ['/workspace', '/coding', '/vibe-coding'],
      matchPrefixes: ['/workbench'],
      order: 20,
      requiredCapability: null,
      featureFlag: null,
      platforms: ['web'],
      minimumReadiness: 'stable',
      offlineAvailable: false,
      requiresProjectContext: false,
      deepLinkRule: 'canonicalWithDescendants',
      selectedStateRule: 'prefix',
      children: [
        {
          id: 'workbench.projects',
          canonicalPath: '/workbench/projects',
          labelKey: 'nav.workbench.projects',
          legacyPaths: ['/workspace'],
          matchPrefixes: ['/workbench/projects'],
          order: 10,
          requiredCapability: null,
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'workbench.editor',
          canonicalPath: '/workbench/editor',
          labelKey: 'nav.workbench.editor',
          legacyPaths: ['/coding'],
          matchPrefixes: ['/workbench/editor'],
          order: 20,
          requiredCapability: 'coding:read',
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'workbench.agents',
          canonicalPath: '/workbench/agents',
          labelKey: 'nav.workbench.agents',
          legacyPaths: ['/vibe-coding'],
          matchPrefixes: ['/workbench/agents'],
          order: 30,
          requiredCapability: null,
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
      ],
    },
    {
      id: 'automations',
      canonicalPath: '/automations/overview',
      labelKey: 'nav.domain.automations',
      iconKey: 'automations',
      legacyPaths: ['/workflows', '/scheduled-tasks', '/subagents', '/discussions'],
      matchPrefixes: ['/automations'],
      order: 30,
      requiredCapability: null,
      featureFlag: null,
      platforms: ['web'],
      minimumReadiness: 'stable',
      offlineAvailable: false,
      requiresProjectContext: false,
      deepLinkRule: 'canonicalWithDescendants',
      selectedStateRule: 'prefix',
      children: [
        {
          id: 'automations.overview',
          canonicalPath: '/automations/overview',
          labelKey: 'nav.automations.overview',
          legacyPaths: [],
          matchPrefixes: ['/automations/overview'],
          order: 10,
          requiredCapability: null,
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'automations.flows',
          canonicalPath: '/automations/flows',
          labelKey: 'nav.automations.flows',
          legacyPaths: ['/workflows'],
          matchPrefixes: ['/automations/flows'],
          order: 20,
          requiredCapability: 'workflow:read',
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'automations.schedules',
          canonicalPath: '/automations/schedules',
          labelKey: 'nav.automations.schedules',
          legacyPaths: ['/scheduled-tasks'],
          matchPrefixes: ['/automations/schedules'],
          order: 30,
          requiredCapability: null,
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'automations.executors',
          canonicalPath: '/automations/executors',
          labelKey: 'nav.automations.executors',
          legacyPaths: ['/subagents'],
          matchPrefixes: ['/automations/executors'],
          order: 40,
          requiredCapability: 'subagent:read',
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'automations.runs',
          canonicalPath: '/automations/runs',
          labelKey: 'nav.automations.runs',
          legacyPaths: ['/discussions'],
          matchPrefixes: ['/automations/runs'],
          order: 50,
          requiredCapability: null,
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonicalWithDescendants',
          selectedStateRule: 'longestPrefix',
        },
      ],
    },
    {
      id: 'library',
      canonicalPath: '/library/capabilities',
      labelKey: 'nav.domain.library',
      iconKey: 'library',
      legacyPaths: [
        '/skills',
        '/plugins',
        '/roles',
        '/role-market',
        '/memory',
        '/experience',
        '/tts',
      ],
      matchPrefixes: ['/library'],
      order: 40,
      requiredCapability: null,
      featureFlag: null,
      platforms: ['web'],
      minimumReadiness: 'stable',
      offlineAvailable: false,
      requiresProjectContext: false,
      deepLinkRule: 'canonicalWithDescendants',
      selectedStateRule: 'prefix',
      children: [
        {
          id: 'library.capabilities',
          canonicalPath: '/library/capabilities',
          labelKey: 'nav.library.capabilities',
          legacyPaths: ['/skills', '/plugins'],
          matchPrefixes: ['/library/capabilities'],
          order: 10,
          requiredCapability: null,
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonicalWithDescendants',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'library.personas',
          canonicalPath: '/library/personas',
          labelKey: 'nav.library.personas',
          legacyPaths: ['/roles', '/role-market'],
          matchPrefixes: ['/library/personas'],
          order: 20,
          requiredCapability: null,
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'library.knowledge',
          canonicalPath: '/library/knowledge',
          labelKey: 'nav.library.knowledge',
          legacyPaths: ['/memory', '/experience'],
          matchPrefixes: ['/library/knowledge'],
          order: 30,
          requiredCapability: 'memory:read',
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'library.voices',
          canonicalPath: '/library/voices',
          labelKey: 'nav.library.voices',
          legacyPaths: ['/tts'],
          matchPrefixes: ['/library/voices'],
          order: 40,
          requiredCapability: null,
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
      ],
    },
    {
      id: 'activity',
      canonicalPath: '/activity/overview',
      labelKey: 'nav.domain.activity',
      iconKey: 'activity',
      legacyPaths: ['/dashboard', '/inbox', '/billing'],
      matchPrefixes: ['/activity'],
      order: 50,
      requiredCapability: null,
      featureFlag: null,
      platforms: ['web'],
      minimumReadiness: 'stable',
      offlineAvailable: false,
      requiresProjectContext: false,
      deepLinkRule: 'canonicalWithDescendants',
      selectedStateRule: 'prefix',
      children: [
        {
          id: 'activity.overview',
          canonicalPath: '/activity/overview',
          labelKey: 'nav.activity.overview',
          legacyPaths: ['/dashboard'],
          matchPrefixes: ['/activity/overview'],
          order: 10,
          requiredCapability: null,
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'activity.inbox',
          canonicalPath: '/activity/inbox',
          labelKey: 'nav.activity.inbox',
          legacyPaths: ['/inbox'],
          matchPrefixes: ['/activity/inbox'],
          order: 20,
          requiredCapability: null,
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
        {
          id: 'activity.usage',
          canonicalPath: '/activity/usage',
          labelKey: 'nav.activity.usage',
          legacyPaths: ['/billing'],
          matchPrefixes: ['/activity/usage'],
          order: 30,
          requiredCapability: 'billing:read',
          featureFlag: null,
          platforms: ['web'],
          minimumReadiness: 'stable',
          offlineAvailable: false,
          requiresProjectContext: false,
          deepLinkRule: 'canonical',
          selectedStateRule: 'longestPrefix',
        },
      ],
    },
  ],
} as const

// 清单是启动期静态契约；结构不合法时必须直接暴露错误，禁止降级为另一套导航。
export const navigationManifest: NavigationManifest = navigationManifestSchema.parse(
  rawNavigationManifest,
)
